import sys, subprocess

DAY = "2026-10-08"

items = [
    ("claude-code", "Claude Code 2.1.292 switches local MCP servers to protocol 2026-07-28 by default",
     "https://mixed-news.com/en/claude-code-2-1-292-stdio-mcp-protocol-2026-07-28-docs-contradict/",
     "2.1.292 (Oct 6) makes the new MCP protocol default on stdio servers while docs still describe rollout wording; adds Agent effort param and --marketplace plugin install flag."),
    ("claude-code", "Claude Code 2.1.290 makes interactive web search budget refillable",
     "https://www.scriptbyai.com/claude-code-timeline/",
     "2.1.290 (Oct 5) replaced the fixed 200-call WebSearch budget with an allowance refilling at 100 calls/hour."),
    ("claude-code", "Claude Code 2.1.291 fixes cloud permission-prompt and session-loss regressions",
     "https://whatsnew.fyi/product/claude-code/releases/v2.1.291",
     "2.1.291 (Oct 6) fixed regressions where cloud sessions dropped permission-prompt answers and session tail messages were lost on quit."),
    ("codex", "Codex Day 1 of 28-day pledge: default output speed up ~50 percent",
     "https://dev.to/hiroki-ii-ai/ai-daily-digest-october-7-2026-codex-ships-day-1-openai-watermarks-text-mistral-goes-le-chonk-1d8a",
     "Oct 5: Day 1 of OpenAI's 28-day Codex pledge raised GPT-6 Astra/6.1 Sol default speed from ~30 to ~50 tok/s via infra optimization, no settings change."),
    ("codex", "OpenCodex v2.76.0 adds per-role model selection for LazyCodex agents",
     "https://undercodenews.com/opencodex-2760-is-a-major-agent-routing-upgrade-lazycodex-gets-smarter-model-selection-claude-integration-deepens-and-account-controls-get-serious-video/",
     "Open-source OpenCodex 2.76.0 (Oct 3) adds model-aware agent delegation: role-specific model selection, auto role sizing, and deeper Claude Code integration."),
    ("codex", "Codex CLI gains parallel agents, worktree forks, voice commands",
     "https://saudishopper.com.sa/en/openai-codex-cli-developer-update/",
     "Updated Codex CLI supports parallel agent management across worktree forks, voice input, a new /agents view, and a full-screen terminal UI."),
    ("meta", "Cequence: Muse traffic at over half of studied customers, poses as ordinary Chrome",
     "https://aapnews.aap.com.au/aapreleases/cision20261008AE66867",
     "Oct 8: Cequence found Muse agent traffic at >50% of customers within two weeks of launch; Muse runs real Chrome in the cloud without identifying as an agent."),
    ("meta", "Muse for Windows native app announced at Microsoft event",
     "https://www.iphoneincanada.ca/2026/10/07/meta-muse-windows-app/",
     "Oct 7: Microsoft announced Muse for Windows as a native app with MXC sandboxing integration; no release date given."),
    ("meta", "Muse gains iPad support plus Canva, Dropbox, Figma, GitHub, Zoom, Asana connectors",
     "https://letsdatascience.com/news/meta-adds-ipad-support-to-muse-3017453a",
     "Oct 7: Muse update adds native iPad app and connectors for Canva, Dropbox, Figma, QuickBooks, GitHub, Zoom, Asana, Klaviyo, Granola, Notion."),
    ("muse", "Meta open-sources Muse Gadgets hardware SDK, gives away 5,000 home hubs",
     "https://pondero.ai/news/2026-10-03-meta-muse-gadgets-sdk/",
     "Oct 2: Apache 2.0 SDKs for ESP32 and Linux let developers wire Muse into custom hardware; 5,000 free Home Link USB-C hubs ship to US subscribers."),
    ("muse", "Meta puts Muse agent on smart glasses with voice wake",
     "https://dev.to/hiroki-ii-ai/ai-daily-digest-october-3-2026-claude-code-mods-muse-on-smart-glasses-dgx-spark-64gb-tesla-olp",
     "Oct 2: Muse comes to smart glasses with Hey Muse voice wake; tasks run in the background until done."),
    ("gemini", "Google retires Gemini Gems, replaces with modular Skills",
     "https://www.webpronews.com/googles-gemini-overhaul-gems-give-way-to-modular-skills-in-major-ai-shift/",
     "Gems phased out in favor of reusable Skills; rollout to Workspace from Oct 5, Gemini app Oct 13, business Gems gone no sooner than Mar 2027."),
    ("gemini", "Google withholds Gemini 4 Argon, limits access to vetted cyber experts and US government",
     "https://www.techjuice.pk/google-gemini-4-argon-restricted-access-safety-cyberattack-concerns/",
     "Oct 1: Argon withheld from public release over cyberattack concerns; phased early access for trusted security researchers and US officials."),
    ("gemini", "Google cuts free Gemini Flash and Pro access starting Oct 9",
     "https://philstartech.com/news/2026/10/07/19959/google-gemini-free-access-flash-pro-october-9/",
     "From Oct 9 free users keep only Flash-Lite; Flash needs AI Plus, Pro needs AI Pro/Ultra."),
    ("openai", "OpenAI and Atlassian expand partnership: frontier models power Rovo and Atlassian agents",
     "https://bytewatchr.com/articles/atlassian-openai-gpt6-rovo-partnership/",
     "Oct 6: GPT-6 family models power agents across Atlassian platform and Rovo via Teamwork Graph; 3,000+ Atlassian devs already use Codex."),
    ("openai", "OpenAI ships Dots: always-on GPT-6 Astra agents with own cloud computers",
     "https://64bit-emdash-site.linuxcontainers.workers.dev/posts/openai-dots-always-on-agents-gpt-6-astra-2026-10-04",
     "Dots rolling out to Pro, Business Premium, Enterprise: persistent agents with dedicated cloud computers and 4,000+ app plugins via ChatGPT, Slack, Teams."),
    ("openai", "OpenAI shelves public launch of GPT-6.1 Astra after missing safety bar",
     "https://imfounder.com/science-tech/tech-news-october-2026-shocking-stories/",
     "GPT-6.1 Astra public launch scrapped after internal tests showed scope and self-reporting issues; DevDay shipped Dots instead."),
    ("anthropic", "Anthropic releases Claude Haiku 5.5: 1M context at $0.10/$0.50 per MTok",
     "https://www.marktechpost.com/2026/10/07/anthropic-releases-claude-haiku-5-5-a-small-model-with-1m-context-priced-at-0-10-per-million-input-tokens/",
     "Oct 7: Haiku 5.5 is Anthropic's fastest, cheapest model with adjustable effort setting, 72.4% on OSWorld 2.1; Sonnet 5.5 cache reads halved."),
    ("anthropic", "OpenAI and Anthropic back mandatory reporting of AI agent data breaches",
     "https://www.cdomagazine.tech/aiml/openai-anthropic-back-mandatory-reporting-of-ai-agent-data-breaches",
     "Oct 6: both labs told Australian lawmakers they support mandatory breach reporting for agent-caused incidents after an unauthorized health-portal access."),
    ("anthropic", "Claude for Google Workspace enters public beta",
     "https://www.scriptbyai.com/anthropic-claude-timeline/",
     "Oct 6: Claude for Google Workspace public beta on all paid plans with sidebar add-on for Docs, Sheets, Slides and new Google file connectors."),
    ("kimi", "Moonshot AI closes final private round at ~$50B, eyes Hong Kong IPO in Q1 2027",
     "https://aiweekly.co/alerts/moonshot-ai-closes-final-private-round-at-50b-eyes-hong-kong-ipo-up-to-5b-in-q1",
     "Bloomberg: Moonshot raised at ~$50B (up from $35B in July), planning up to $5B HK IPO in Q1 2027 with Alibaba and Tencent backing."),
    ("kimi", "Moonshot AI targets $2B revenue as Kimi usage softens",
     "https://www.renascence.io/news/61911/moonshot-ai-sets-2b-revenue-target-as-kimi-usage-softens",
     "Oct 5: Moonshot targets $2B annual revenue despite slight dip in K3 usage; still ~300B tokens/day on OpenRouter."),
    ("kimi", "Moonshot investigates researcher claim Kimi could be coaxed into bioweapon and assassination instructions",
     "https://foxnews.com/tech/chinese-ai-model-investigated-researcher-says-provided-instructions-bioweapons-assassinations",
     "Moonshot launched an internal investigation after a researcher demonstrated Kimi manipulated into providing WMD and attack-planning instructions."),
    ("minimax", "FreeVideo v0.2.0 runs MiniMax H3 video model on 8GB GPUs",
     "https://affmarketingworld.com/news/freevideo_minimax_h3_8gb",
     "Oct 5: open-source FreeVideo runs MiniMax H3 video AI on consumer 8GB cards via weight streaming; ~9-10 min per 10s clip."),
    ("minimax", "MiniMax M3.1 Flash Preview ships with no pricing or model card",
     "https://tech-insider.org/minimax-m3-1-vs-gpt-6-luna-vs-deepseek-v4-1-flash-2026/",
     "Sep 27: M3.1 Flash Preview launched in MiniMax Code with 1M context and 5 reasoning-effort levels, but no published price or benchmarks."),
    ("glm", "Amazon Bedrock adds Zhipu's GLM-5.3 under revenue-sharing deal",
     "https://startupfortune.com/amazon-bedrock-adds-zhipus-glm-53-under-a-revenue-sharing-deal/",
     "Oct 5: GLM-5.3 lands on Amazon Bedrock, letting enterprises use the coding/agent model with existing AWS compliance and billing."),
    ("glm", "Malaysia's YTL launches ILMUcode desktop coding agent on ILMU-GLM-5.3",
     "https://gotchaa-lab.com/blog/2026-10-03-ilmucode-glm-5-3-sovereign-ai-coding",
     "Oct 1: YTL AI Labs launched ILMUcode, an AI coding desktop app on a Z.ai-partnered ILMU-GLM-5.3 model with data processed in Malaysia."),
    ("mistral", "Mistral releases Mistral Large 4 'Le Chonk': 1.05T-param open MoE preview",
     "https://www.marktechpost.com/2026/10/06/mistral-ai-releases-mistral-large-4-le-chonk-a-1-05t-parameter-open-weight-multimodal-moe/",
     "Oct 6: Mistral Large 4 public preview - 1.05T params, 49B active, 1M context, $1.36/$4.18 per MTok; weights promised by end of October."),
]

added = 0
for beat, title, url, summary in items:
    r = subprocess.run(
        ["python3", "/home/hatch/workspace/agentic-radar/radar/collect.py", "add",
         DAY, beat, title, "--url", url, "--summary", summary],
        capture_output=True, text=True)
    if r.returncode != 0:
        print(f"FAILED {beat}: {title}\n{r.stderr}")
    else:
        added += 1
print(f"added {added}/{len(items)}")
